[wiki]

# copy images and point src to MW instance
# true | false
media = false

# set what's the article to use for the frontpage
frontpage = "Hackers & Designers"

# as a TOML illiterate this seemed the most reasonable setup: apologies if not!
# please fill out all fields, including "label" even if you set `nav: false`

[wiki.categories.Article]
parse = true
nav = false
fallback = true
label = "Articles"
[wiki.categories.Event]
parse = true
nav = false
fallback = false
label = "Events"
[wiki.categories.Collaborators]
parse = true
nav = true
fallback = false
label = "Collaborators"
[wiki.categories.Publishing]
parse = true
nav = true
fallback = false
label = "Publishing"
[wiki.categories.Tools]
parse = true
nav = true
fallback = false
label = "Tools"

[tool-plugin]
host_default = 'github'
host = { github = ['https://raw.githubusercontent.com', 'https://github.com'] }
branch_default = ['main', 'master']